### ISSUE TITLE
Clickable buttons to initialise skill check

### ISSUE THREAD

**Issue by M4leph1st0** [Khaali-dev/wilderfeast#1]
While triggering the skill check wih rmb is fine and functional, it also is a bit unintuitive. It would be a good idea to make the styles clickable with them prompting the skill check, if you haven't already planned this for future releases.

**Comment by Khaali-dev** [comment]
I understand the issue but I'm not sure about changing that, because right click menu is used at several places in the sheet and I think it's important to have consistency.

**Comment by M4leph1st0** [comment]
I understand you wanting consistency, maybe it's just me coming from systems that primariliy utilize lmb to trigger rolls that makes it feel unintuitive. I will close the issue and try to adjust personally.
Thank you for your great work so far.

**Comment by M4leph1st0** [comment]
Not planned, because of concerns regarding consistency
